### ISSUE TITLE
cannot import name 'SchemaJit'

### ISSUE THREAD

**Issue by vklap** [lyft/toasted-marshmallow#12]
Hi,

When defining the Jit in the Meta class:

```
class BaseSchema(Schema):
    class Meta:
        jit = toastedmarshmallow.Jit
```
Then I can the following error at runtime:

> ImportError: cannot import name 'SchemaJit'

Thanks

**Comment by smith-m** [comment]
what was the resolution here? I'm running into the same issue with 
toastedmarshmallow==0.2.6
marshmallow==2.15.3

**Comment by vklap** [comment]
I think that you should make sure you import only toastedmarshmallow - becuase toastedmarshmallow already forked/copied mashmallow inside its code base.

So, basically, I hope that if you run the following uninstall and install commands, it should work:

`
pip uninstall marshmallow==2.15.3
pip install toastedmarshmallow==0.2.6
`
