### ISSUE TITLE
Provide a non-binary Source distribution on PyPI

### ISSUE THREAD

**Issue by haroldfredshort** [lyft/toasted-marshmallow#6]
Most projects on PyPI have a Source distribution available as a *.tar.gz file, in addition to any *.whl or *.egg files. This prevents something like this, "pip install --no-binary=:all: -r requirements.txt", from working for me when toasted-marshmallow is in my requirements. I can work around this, but would greatly appreciate not needing to for this package. If it is any consolation, I am already using toasted-marshmallow in production.

**Comment by rowillia** [comment]
Fixed!  Thanks for the report!

**Comment by haroldfredshort** [comment]
Awesome! Thank you!
